### PR TITLE
Added support for Jetpack's infinite scroll

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #18 

@Misplon please test this and let me know if there are any bugs or need for any styling changes. Thanks.

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks @adiraomj.

Can we perhaps use a different loop so we can change the styling. I think, ideally, we'd like the post thumbnails to load inside a single container vs having a new container load each time:

container

Can you also take a quick look at the setup when you go to Settings > Reading and disable: Infinite Scroll Behavior.

Should we perhaps center the Older Posts button?

**Comment by adiraomj** [comment]
Changes:
Added new file to handle infinite scroll loop.
Added id `main-loop` to loop container.
Made necessary styling changes.

@Misplon please have a look and let me know. Thanks.

We can handle older posts styling  in a separate PR.

**Comment by Misplon** [comment]
Awesome :) Nicely done. The older posts button alignment, I think, should be part of this PR because it appears when you change the infinite scroll behaviour from Settings > Reading by disabling the Infinite Scroll Behavior checkbox. We're nearly there, we just need a small margin fix:

older-posts

Perhaps just:

`#inifinite-handle { margin-bottom: 25px; }
`

**Comment by Misplon** [comment]
@adiraomj nearly done here, just that last little spacing we chatted about on Slack.

**Comment by adiraomj** [comment]
Done. Sorry for the delay. :)

**Pull request merged**
