### PR TITLE
Icons

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancements #12, #13, #16 

- Added icon font called _focus_. I used icons from font awesome.
- Changed masthead search icon from background image to icon font. ( Now uses JS )
- Added arrows for navigation of single posts, @Misplon I haven't added any color yet. What do you think? Also let me know if the size is ok.
- The arrow icon has a setting which is off by default.
- Added settings to allow users to replace icons with images.

### CODE REVIEW

**Comment by Misplon** [comment]
Awesome, thanks for the big push here.

# **Single Post Navigation Arrows**

**Possible Settings Confusion**
I think we'll need to differentiate this setting from the one at Theme Settings > General > Display Post Navigation. Let's expand the description of the original setting:

_Display next and previous post links on at the bottom of post single pages._

**Icon Styling**
My thought with the left / right icon is to match it up with the style of the home page play button. Should we perhaps, try: http://fontawesome.io/icon/arrow-circle-right/ and left.

For color, can we please, try white with a reduced opacity default and then full opacity on hover. I'm imaging the buttons being quite subtle until you hover over them. Let me know your thoughts.

Should we consider constraining the icons so that if users add a big image it will be constrained?

**Comment by adiraomj** [comment]
I'll make the changes.

Constraining the icons is a good idea. Otherwise we could have issues with responsiveness. Will do it.

**Comment by Misplon** [comment]
Awesome, thanks :)

**Comment by adiraomj** [comment]
@Misplon please have a look now. Thanks

**Pull request merged**
